
export const redirectConfig = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  users: "/users",
  cinemas: "/cinemas",
  cinemaDetail: (id: string | number) => `/cinemas/${id}/detail`,
  cinemaRooms: (id: string | number) => `/cinemas/${id}/rooms`,
  cinemaStatic: "/cinemas/static",
  createMovie: "/movies/create",
  movies: "/movies",
  movieDetail: (id: string | number) => `/movies/${id}/detail`,
  movieStatic: "/movies/static",
  movieUpdate: (id: string | number) => `/movies/${id}/update`,
  rooms: "/rooms",
  createRoom: "/rooms/create", 
  roomDetail: (id: string | number) => `/rooms/${id}/detail`,
  roomUpdate: (id: string | number) => `/rooms/${id}/update`,
  roomStatic:"/rooms/static",
  seats: "/seats",
  showtimes: "/showtimes",
  createShowTime: "/showtimes/create", 
  showtimeDetail: (id: string | number) => `/showtimes/${id}/detail`,
  showtimeUpdate: (id: string | number) => `/showtimes/${id}/update`,
  showtimeStatic: "/showtimes/static",
  tickets: "/tickets",
  seatReservation: "/seat-reservation",
  combos: "/combos",
  discounts: "/discounts",
  points: "/points",
  contents: "/contents",
  settings: "/settings",
};
