export const redirectConfig = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  cinemas: "/cinemas",
  cinemaDetail: (id: string | number) => `/cinemas/${id}/detail`,
  movies: "/movies",
  rooms: "/rooms",
  seats: "/seats",
  showtimes: "/showtimes",
  tickets: "/tickets",
  seatReservation: "/seat-reservation",
  combos: "/combos",
  discounts: "/discounts",
  points: "/points",
  contents: "/contents",
  users: "/users",
  settings: "/settings",
};
